installers:
  - name: brew
  - name: asdf
  - name: sdk
  - name: pipx
  - name: nvm
  - name: pyenv
  - name: tfenv

packages:
  - name: zsh
    installer: brew
  - name: git
    installer: brew
  - name: dos2unix
    installer: brew
  - name: jq
    installer: brew
  - name: yq
    installer: brew
  - name: unzip
    installer: brew
  - name: coreutils
    installer: brew
  - name: gnupg
    installer: brew
  - name: bison
    installer: brew
  - name: gettext
    installer: brew
  - name: gnu-tar
    installer: brew
  - name: zlib
    installer: brew
  - name: curl
    installer: brew
  - name: awscli
    installer: brew
  - name: serverless
    installer: brew
  - name: direnv
    installer: asdf
  - name: helm
    installer: asdf
    version: 3.3.4
    plugins:
      - https://github.com/hypnoglow/helm-s3.git
      - https://github.com/databus23/helm-diff
  - name: helmsman
    installer: asdf
    version: 3.4.4
  - name: kubectl
    installer: asdf
    version: 1.19.2
  - name: nodejs
    installer: asdf
    version: 14.13.0
  - name: packer
    installer: asdf
    version: 1.6.4
  - name: python
    installer: asdf
    version: 3.8.5
  - name: poetry
    installer: asdf
  - name: terraform
    installer: asdf
    version: 0.12.29
  - name: java
    installer: sdk
    version: 11.0.8-amzn
  - name: groovy
    installer: sdk
    version: 3.0.6
#  - name: aws-sso-credential-process
#    installer: pipx
