installers:
  - name: asdf
  - name: tfenv
  - name: nvm
  - name: pyenv
  - name: pipx
  - name: sdk

packages:
  ## native
  - name: vim
  - name: wget
  - name: less
  - name: tar
  - name: zip
  - name: unzip
  - name: curl
  - name: git
  - name: jq
  - name: awscli
  - name: dos2unix

  ## asdf
  - name: packer
    installer: asdf
    version: 1.6.4
  - name: helm
    installer: asdf
    version: 3.3.4
  - name: helmsman
    installer: asdf
    version: 3.4.4
  - name: kubectl
    installer: asdf
    version: 1.19.2

  ## tfenv
  - name: terraform
    installer: tfenv
    version: 0.12.29

  ## sdk
  - name: java
    installer: sdk
    version: 11.0.8-amzn
    requires:
      - zip
  - name: groovy
    installer: sdk
    version: 3.0.6

  ## nvm
  - name: nodejs
    installer: nvm
    version: 12.19.0

  ## pyenv
  - name: python
    installer: pyenv
    version: 3.7.2
    requires:
      - bzip2
      - libffi-dev
      - sqlite3

  ## pipx
  - name: poetry
    installer: pipx
  - name: aws-sso-credential-process
    installer: pipx
  - name: awscurl
    installer: pipx
